# -*- coding: utf-8 -*-
"""Digital Image Processing Engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_P3H-ugj5mA5aYHrrSer4vMG26_FXzSj
"""

import numpy as np
from PIL import Image, ImageEnhance, ImageChops

img = Image.open('/content/image.jpg')
grayscale_img = img.convert('L')
grayscale_img.save('/content/grayscale_image.jpg')

enhancer = ImageEnhance.Brightness(img)
brighten_img = enhancer.enhance(1.2)
brighten_img.save('/content/brighten_image.jpg')

invert_img = ImageChops.invert(img)
invert_img.save('/content/invert_image.jpg')

img_array = np.array(img)
cropped_array = img_array[100:400, 100:400]

result_image = Image.fromarray(cropped_array)
result_image.save('/content/cropped_image.jpg')

